<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bayar</name>
   <tag></tag>
   <elementGuidId>7d79057c-ef46-4d03-ab51-d4f47f4304e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coachmark4']/button/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-adf4w5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97eab75c-63bd-4c39-89c5-7bf422b87a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-adf4w5</value>
      <webElementGuid>940c26bb-c031-4e77-8787-6a6fbe33f540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bayar</value>
      <webElementGuid>67c4318f-5f8e-4e08-8dd1-e6f87e21aff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coachmark4&quot;)/button[@class=&quot;css-15l5nyw-unf-btn eg8apji0&quot;]/span[1]/div[@class=&quot;css-adf4w5&quot;]</value>
      <webElementGuid>63bd3d74-b92e-494e-aad0-3897dcb13c6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coachmark4']/button/span/div</value>
      <webElementGuid>2a07972f-a8e8-492a-9b6d-d2a926d22005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Makin hemat pakai promo'])[1]/following::div[29]</value>
      <webElementGuid>b03c0eaf-17ca-4ab3-b2a6-9d1b4d77a46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utama'])[1]/following::div[71]</value>
      <webElementGuid>2f0175ff-3363-4c72-b747-9a1029aef8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Tokopedia'])[2]/preceding::div[1]</value>
      <webElementGuid>c0b88411-9d32-45a7-b583-20271976ac69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hak Kekayaan Intelektual'])[1]/preceding::div[1]</value>
      <webElementGuid>67f12878-7c3a-4c1c-a421-9f27e8cba4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar']/parent::*</value>
      <webElementGuid>0071c4de-648d-4e57-b2dd-903f22355cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/div</value>
      <webElementGuid>9cd8e0a7-ede8-46cc-bdad-09e36abf0342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bayar' or . = 'Bayar')]</value>
      <webElementGuid>19ed49de-ad0b-4fae-b218-1fcb3b6b9d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
