<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Pilih pembayaran_iframe-occ-change-payment</name>
   <tag></tag>
   <elementGuidId>73fd4a5e-43ab-4a80-9423-9928df8509d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='iframe-occ-change-payment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;iframe-occ-change-payment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>98a600cd-6f86-4e7c-9d19-bd6762ddc4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframe-occ-change-payment</value>
      <webElementGuid>d4703771-268b-4c5c-8d6e-c558a20b8f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>iframe-occ-change-payment</value>
      <webElementGuid>d615a22d-67d9-4ad3-a686-2b88e6483e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;css-1g5w2rw&quot;]/div[10]/div[@class=&quot;css-7lpkml e1nc1fa20&quot;]/article[@class=&quot;css-z3221k-unf-modal e1nc1fa21&quot;]/div[@class=&quot;css-d6mneo e1nc1fa22&quot;]/div[1]/div[@class=&quot;css-tixlo0&quot;]/iframe[1]</value>
      <webElementGuid>c83910bc-d6ed-42da-bf77-65ca45836d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='iframe-occ-change-payment']</value>
      <webElementGuid>36e411a6-7781-4384-8a26-cb48fd306273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>11f19af0-2ccb-430e-8904-72d36803603f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'iframe-occ-change-payment' and @title = 'iframe-occ-change-payment']</value>
      <webElementGuid>8aad9770-8e87-40fb-95a3-29aadfa8dc8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
