<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mitra Tokopedia</name>
   <tag></tag>
   <elementGuidId>57298200-ede0-4bf0-8daa-0a40d5ac570d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c1d9472-e92a-4d43-8077-c51e384d9846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mitra</value>
      <webElementGuid>bbc6d8ad-6174-4c63-b85a-02b0a1164374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>76da1220-279a-4370-9555-e1b138b3b576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>3aa87ad1-0cc6-4ebb-9163-c028baf9c912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1wx1rev</value>
      <webElementGuid>e75297b2-3aab-4061-8267-5b45ba263cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnHeaderMitra</value>
      <webElementGuid>a983e285-a070-4823-a4ec-408a438854bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mitra Tokopedia</value>
      <webElementGuid>4d06b7c3-ee80-43c9-abc9-97c764a6e399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-jdif88 edxse4c2&quot;]/div[@class=&quot;css-wga40m edxse4c4&quot;]/a[@class=&quot;css-1wx1rev&quot;]</value>
      <webElementGuid>8cb3302d-8e5f-440f-bc9c-0e9c6e11e39e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div/div[2]/a[2]</value>
      <webElementGuid>58731602-1eb3-4a88-8d5d-7240e2bbcaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mitra Tokopedia')]</value>
      <webElementGuid>84e3e09c-f934-490a-9e1a-ad8d4eeb53b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Tokopedia'])[1]/following::a[1]</value>
      <webElementGuid>f32d2523-218c-401b-9f59-08bef91d30e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Edukasi Seller'])[1]/preceding::a[1]</value>
      <webElementGuid>da51d26a-2bc1-4981-8019-49dd2f373fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/preceding::a[2]</value>
      <webElementGuid>c4d76977-7a96-4495-b891-6a71b9f3d78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mitra Tokopedia']/parent::*</value>
      <webElementGuid>7987198d-c123-4690-89db-39051163a458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mitra')]</value>
      <webElementGuid>34447636-97a7-4ed9-9fce-ce2beff854a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>c96d5c08-99d5-4c31-aac5-12021d0bd496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mitra' and (text() = 'Mitra Tokopedia' or . = 'Mitra Tokopedia')]</value>
      <webElementGuid>0d642f57-49da-4720-95f1-9c8eff86d4b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
