<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rp120.704</name>
   <tag></tag>
   <elementGuidId>b8aea06b-d034-4c00-b580-a2a402766315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='express-pemuda-balance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#express-pemuda-balance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d89a02ac-ff70-4c81-98ed-51953fbe7e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment__detail payment__detail-center</value>
      <webElementGuid>f4b9c0bc-c984-4a98-920f-ee493fedeed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>express-pemuda-balance</value>
      <webElementGuid>87f8ba52-7efb-48a3-ae2e-b1d317556004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp120.704</value>
      <webElementGuid>19e3ac2f-6536-4b94-a64d-336b34223677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;express-pemuda-balance&quot;)</value>
      <webElementGuid>c6251d15-b4d1-40a3-8678-009728099144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Jual AccentAmbios - 20s Tshirt Kaos Boxy Oversize Pria Wanita StayReal - S - Kota Bandung - AccentAmbios  Tokopedia/iframe_Pilih pembayaran_iframe-occ-change-payment</value>
      <webElementGuid>34d07b21-acf6-40d4-9aa6-ea378901bcc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='express-pemuda-balance']</value>
      <webElementGuid>1e824737-a796-45a6-8b81-3280b5848426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div/div/div[2]</value>
      <webElementGuid>ec9b2823-942b-45b8-807f-741dcbe7881d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran di Tokopedia'])[1]/following::div[6]</value>
      <webElementGuid>4bee53e7-ffb7-4e18-99bc-1487630fbe83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti Metode Pembayaran'])[1]/following::div[21]</value>
      <webElementGuid>1d03cd8a-d368-47bc-92ec-e0af9f238cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Kredit'])[1]/preceding::div[5]</value>
      <webElementGuid>70e10729-4aa7-405a-b996-8030d59416f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>676a9201-528c-4120-95dd-3ffa727b5728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'express-pemuda-balance' and (text() = 'Rp120.704' or . = 'Rp120.704')]</value>
      <webElementGuid>9cfe4c18-4916-42f2-ad2a-3fa6ee4231aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
