<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Saldo tidak cukup_express-icon-arrow-right</name>
   <tag></tag>
   <elementGuidId>7f21dff0-81dc-4842-bcae-7656ee8d24c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div[2]/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.express-icon-arrow-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6aafa8c-0a7e-4640-ad7a-d28090741950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>express-icon-arrow-right</value>
      <webElementGuid>acc63a98-b0b0-43c5-abd0-039931a301a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;payment__list-wrapper&quot;]/div[@class=&quot;payment-list express-payment-list&quot;]/div[@class=&quot;payment__list&quot;]/div[@class=&quot;payment__selection&quot;]/div[@class=&quot;express-icon-arrow-right&quot;]</value>
      <webElementGuid>b5cbfa93-ca36-48c8-9f63-91f9780bf7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Jual AccentAmbios - 20s Tshirt Kaos Boxy Oversize Pria Wanita StayReal - S - Kota Bandung - AccentAmbios  Tokopedia/iframe_Pilih pembayaran_iframe-occ-change-payment</value>
      <webElementGuid>c68efbc7-132d-4ec3-99e3-004979b0fa50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div/div/div[2]/div</value>
      <webElementGuid>f00255dd-655f-4941-b673-a75bb4a5d5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>9dda3b8e-9556-4d8f-b12a-5c4ab699269f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
