<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Total TagihanRp108.700</name>
   <tag></tag>
   <elementGuidId>8d735410-5d6e-4723-91ee-c0cc865bee10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div/div[2]/div/div/div/div/section/div[2]/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e10fe749-6f37-4b40-9a52-a1e715f9da77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15lnn05</value>
      <webElementGuid>13c42fb2-a055-486c-b9c4-76ae547dfc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total TagihanRp108.700</value>
      <webElementGuid>68b91e25-26c2-438a-a009-f3a1ab41510f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-13qxrs6 mother-container&quot;]/div[@class=&quot;mother-container-flex&quot;]/div[@class=&quot;mother-container-right-side&quot;]/div[@class=&quot;css-1ihpmz5&quot;]/div[@class=&quot;summary-positioner&quot;]/div[@class=&quot;summary-wrapper summary-position-initiated&quot;]/div[@class=&quot;fixed-wrapper&quot;]/section[@class=&quot;sidebar-card css-y1w77o-unf-card eeeacht0&quot;]/div[2]/div[@class=&quot;css-15lnn05&quot;]</value>
      <webElementGuid>eee4b54a-2c15-4cf4-b3ea-bba4fd94abc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div/div[2]/div/div/div/div/section/div[2]/div[5]</value>
      <webElementGuid>308ea5ba-d75c-44fa-bb3d-f1228acae12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Makin hemat pakai promo'])[1]/following::div[20]</value>
      <webElementGuid>438c52a4-c247-4f3c-ab24-3869cc41f911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utama'])[1]/following::div[62]</value>
      <webElementGuid>be52d182-c312-48f5-9e43-b45d1adf45a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar'])[1]/preceding::div[2]</value>
      <webElementGuid>f9a38588-1875-43cd-87fd-74334635ad4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Tokopedia'])[2]/preceding::div[5]</value>
      <webElementGuid>12ea3c1f-a5c8-4e0e-94d0-6a957a767bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div[5]</value>
      <webElementGuid>6a111af2-8c80-4c45-bae0-01534a49dbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Total TagihanRp108.700' or . = 'Total TagihanRp108.700')]</value>
      <webElementGuid>3b94f45b-a347-4acb-99f5-adbb675fbcfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
