<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OVO CashSaldo tidak cukup Rp4.811</name>
   <tag></tag>
   <elementGuidId>f79c77b8-bca2-43c4-bfa5-bcd2898a488f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3']/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.payment-list.express-payment-list.disabled > div.payment__list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c21ceb38-dd32-4ce9-ac16-be928c8f6b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment__list</value>
      <webElementGuid>6a6ecd76-8534-4d79-bb51-6b961f9d1538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OVO CashSaldo tidak cukup: Rp4.811</value>
      <webElementGuid>6c215c96-6a40-4696-af44-7047dd7b753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/div[@class=&quot;payment__list-wrapper&quot;]/div[@class=&quot;payment-list express-payment-list disabled&quot;]/div[@class=&quot;payment__list&quot;]</value>
      <webElementGuid>ad777a8c-005a-407f-b683-b5d926c28d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Jual AccentAmbios - 20s Tshirt Kaos Bo_ee17a9/iframe_Pilih pembayaran_iframe-occ-change-payment</value>
      <webElementGuid>af073cfa-cd50-43b5-9354-091b8ee4623e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div[2]/div/div</value>
      <webElementGuid>7330eb60-d5d7-4ed6-b9be-9ec40e4a05ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran Instan'])[1]/following::div[3]</value>
      <webElementGuid>e6c747b8-f1f3-49d6-9c0e-e4948ca69369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan pembayaran lain'])[1]/following::div[5]</value>
      <webElementGuid>faf79069-7e09-4c4f-a729-0f867ae034ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div</value>
      <webElementGuid>e782b929-903c-482b-8288-269d72a36076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OVO CashSaldo tidak cukup: Rp4.811' or . = 'OVO CashSaldo tidak cukup: Rp4.811')]</value>
      <webElementGuid>77de8df2-5eb9-477d-ac68-471dab1932d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
