<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Pilih pembayaran_iframe-occ-change-payment</name>
   <tag></tag>
   <elementGuidId>8e4d326a-a349-4199-8b20-e479062f3466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='iframe-occ-change-payment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;iframe-occ-change-payment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5f368210-eaac-4071-a749-864c4b471d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iframe-occ-change-payment</value>
      <webElementGuid>b1ef80b2-aaa8-44b9-9d1b-906e35dfd4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>iframe-occ-change-payment</value>
      <webElementGuid>8a22df70-4fec-484e-af82-f926555f6d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;css-1g5w2rw&quot;]/div[10]/div[@class=&quot;css-7lpkml e1nc1fa20&quot;]/article[@class=&quot;css-z3221k-unf-modal e1nc1fa21&quot;]/div[@class=&quot;css-d6mneo e1nc1fa22&quot;]/div[1]/div[@class=&quot;css-tixlo0&quot;]/iframe[1]</value>
      <webElementGuid>cdcecb32-b6fc-4090-bc22-7d3a23ec44d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='iframe-occ-change-payment']</value>
      <webElementGuid>2a782c9a-128b-4190-be38-e18c71dbf2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>4c73b794-9b85-4d62-8a96-3cb171cf8160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'iframe-occ-change-payment' and @title = 'iframe-occ-change-payment']</value>
      <webElementGuid>07f3c8bf-cc64-46a8-931d-c8a5d37d7ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
