<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rp120.704</name>
   <tag></tag>
   <elementGuidId>d88a5f97-61f1-4528-a190-07b953873228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='express-pemuda-balance']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.payment__name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0162d34-ab26-4e0f-bc62-08c899a6e3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment__name</value>
      <webElementGuid>1a8d672a-4775-4c2b-a4a5-5fdb15e94738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp120.704</value>
      <webElementGuid>747b8099-35be-4034-9070-8fc2333d5240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;express-pemuda-balance&quot;)/div[@class=&quot;payment__name&quot;]</value>
      <webElementGuid>787774a0-cb56-44da-84d9-5c645b68334f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Jual AccentAmbios - 20s Tshirt Kaos Boxy Cut Oversize Pria Wanita BTBAwesom - XL - Kota Bandung - AccentAmbios  Tokopedia/iframe_Pilih pembayaran_iframe-occ-change-payment</value>
      <webElementGuid>96bfa24a-b0b5-4897-8b2c-97882d584abf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='express-pemuda-balance']/div</value>
      <webElementGuid>8db7039f-ddb0-41c9-a696-3e6bc28d6529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran di Tokopedia'])[1]/following::div[7]</value>
      <webElementGuid>051f5077-338b-48b3-bfc1-38bdf590d79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti Metode Pembayaran'])[1]/following::div[22]</value>
      <webElementGuid>394f49ad-3200-462a-8b1d-e548d76b9d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Kredit'])[1]/preceding::div[4]</value>
      <webElementGuid>5b9c4552-8547-4b5e-b6a6-1c42b5f970b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Kredit / Cicilan'])[1]/preceding::div[6]</value>
      <webElementGuid>72fdfbed-ce27-4dd4-86fd-f5abb9d79a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp120.704']/parent::*</value>
      <webElementGuid>785ee7a8-3e9c-4d87-8cd4-5c13cd3bb0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>de75bbb6-733a-42b5-a337-f719d5a2d952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rp120.704' or . = 'Rp120.704')]</value>
      <webElementGuid>1917ba7d-ab9d-4494-be1b-f94677302c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
