<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_BCA Virtual Account</name>
   <tag></tag>
   <elementGuidId>fab8bbf5-25b1-4daa-8bb3-7dc549c14571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onboarding-remove-profile-1-1']/div/div/div[3]/div/div/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.payment-title.css-1qifx2t-unf-heading.e1qvo2ff8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>603cf45b-721d-4afa-80a6-1819de65593a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>98ced9f5-bdf4-4637-861b-8733850fb3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>paymentTitleText</value>
      <webElementGuid>5d70c3f8-94d8-418c-990b-dc749588d5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-title css-1qifx2t-unf-heading e1qvo2ff8</value>
      <webElementGuid>68c01753-0b19-4ba3-b236-1a940a33e9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCA Virtual Account</value>
      <webElementGuid>fff0171c-0eb5-4aa7-a8cf-5e208c7d22bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboarding-remove-profile-1-1&quot;)/div[1]/div[@class=&quot;css-7e4vat&quot;]/div[@class=&quot;css-1k3qxju&quot;]/div[1]/div[1]/div[@class=&quot;css-10x2f60&quot;]/div[@class=&quot;css-70qvj9&quot;]/div[2]/p[@class=&quot;payment-title css-1qifx2t-unf-heading e1qvo2ff8&quot;]</value>
      <webElementGuid>54a5d458-7b00-44da-afb2-ad0c47b34917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onboarding-remove-profile-1-1']/div/div/div[3]/div/div/div/div/div[2]/p</value>
      <webElementGuid>18e94bb0-c7e3-4b30-a335-bf44ec87383d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utama'])[1]/following::p[10]</value>
      <webElementGuid>b3a40b91-ad85-4ca6-919f-5ac46e2bca53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Makin hemat pakai promo'])[1]/preceding::p[3]</value>
      <webElementGuid>6fee2be2-2a07-43ca-a09d-9eeabb4d6e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar'])[1]/preceding::p[21]</value>
      <webElementGuid>97895f4b-06e0-440f-a8bf-109571fc723d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BCA Virtual Account']/parent::*</value>
      <webElementGuid>d08f1ac8-bbdf-4446-ad4b-f7a5e0832dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/p</value>
      <webElementGuid>262bdcf7-e3ca-4199-94e0-ec0646b5c773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'BCA Virtual Account' or . = 'BCA Virtual Account')]</value>
      <webElementGuid>8209bae2-4200-4ff5-9ff9-52b69c06f58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
