<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Kota Bandung_css-1q90pod</name>
   <tag></tag>
   <elementGuidId>94e5defc-7b5c-407e-919d-5e43dc4414af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/section[2]/div/section/div[3]/div/div/div/div[3]/div/div/div/div/div/div/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5871f582-726c-4f55-891c-c2c3a17185b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1q90pod</value>
      <webElementGuid>4524729c-72f0-4101-baea-fecea33d8b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/300-square/VqbcmM/2023/10/15/3a43852a-50aa-4c82-897c-125082ce9c22.jpg</value>
      <webElementGuid>addfde62-2e12-433d-9e90-27056150bcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AccentAmbios - 20s Tshirt Kaos Boxy Oversize Pria Wanita StayReal</value>
      <webElementGuid>b9721a8a-f891-4712-a58a-64e70df2c373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>imgLeftCarouselProduct</value>
      <webElementGuid>0b64af39-7424-4db0-9b16-35b9aff6ad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/main[@class=&quot;css-15x0u31&quot;]/section[@class=&quot;css-stopwq&quot;]/div[@class=&quot;css-183zhx4&quot;]/section[@class=&quot;css-12ctp9m-unf-card eeeacht0&quot;]/div[@class=&quot;css-17ufkuw&quot;]/div[@class=&quot;css-zgsss css-1sv3lfz&quot;]/div[@class=&quot;css-ztvvor&quot;]/div[@class=&quot;css-10p3cwr carousel&quot;]/div[@class=&quot;css-l3n1jj&quot;]/div[@class=&quot;css-sncotz center&quot;]/div[1]/div[@class=&quot;css-1u6yi94&quot;]/div[@class=&quot;css-1x9x50q&quot;]/div[@class=&quot;css-twpy6c&quot;]/div[@class=&quot;prd_container-card css-1jjecph&quot;]/div[@class=&quot;pcv3__container css-1izdl9e&quot;]/div[@class=&quot;css-19oqosi&quot;]/a[1]/div[@class=&quot;pcv3_img_container css-1mygogd&quot;]/img[@class=&quot;css-1q90pod&quot;]</value>
      <webElementGuid>0730f406-5c2b-4d78-ad30-732fb78910d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section[2]/div/section/div[3]/div/div/div/div[3]/div/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>a2a3842c-dd77-42ab-a6a1-9173ea0a70a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AccentAmbios - 20s Tshirt Kaos Boxy Oversize Pria Wanita StayReal']</value>
      <webElementGuid>a1b29699-97a1-4735-abc4-eb572f4617c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>cbcfccb4-7eeb-4756-8ab2-2ce5b72bf7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/cache/300-square/VqbcmM/2023/10/15/3a43852a-50aa-4c82-897c-125082ce9c22.jpg' and @alt = 'AccentAmbios - 20s Tshirt Kaos Boxy Oversize Pria Wanita StayReal']</value>
      <webElementGuid>097b7248-1b4e-4543-86ac-b196f5be4de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section[2]/div/section/div[3]/div/div/div/div[5]/div/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>c3723392-baf3-4145-bf42-db0a6e9c2bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AccentAmbios - 20s Tshirt Kaos Boxy Cut Oversize Pria Wanita BTBAwesom']</value>
      <webElementGuid>3f092d4b-e3d9-4110-b3c4-0dcb23ed6ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>21de1d61-c8f2-4b94-93d5-e85c13b2f752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/cache/300-square/VqbcmM/2023/8/5/9c7d5662-b785-4155-8fe4-90ebdba16445.jpg' and @alt = 'AccentAmbios - 20s Tshirt Kaos Boxy Cut Oversize Pria Wanita BTBAwesom']</value>
      <webElementGuid>388824ce-1ec4-43be-b36b-351ff2430537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
