<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Toko_css-13emzbn</name>
   <tag></tag>
   <elementGuidId>ac1793d8-ab7d-4096-b45c-f2b08910ae7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-profile-header']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#my-profile-header > div.css-14ezpfl > img.css-13emzbn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3cc2d72b-2e7e-47b7-b973-9dfae4d5334c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-13emzbn</value>
      <webElementGuid>06b28eff-0bd9-4919-abfd-2f1e3e0094f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/300/tPxBYm/2023/12/21/e223defa-a09f-4c36-b908-ab718a069745.png</value>
      <webElementGuid>7bc59cea-1dd8-42b5-8006-ee3c9b38ae66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Al</value>
      <webElementGuid>65390959-78ce-4bf2-97cb-dfeed2f96439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-profile-header&quot;)/div[@class=&quot;css-14ezpfl&quot;]/img[@class=&quot;css-13emzbn&quot;]</value>
      <webElementGuid>5fca5f81-ab91-41db-865b-bd21caf60e2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-profile-header']/div/img</value>
      <webElementGuid>9a32fbcd-99ec-48cd-bca7-4fe3882ece85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Al']</value>
      <webElementGuid>c0af3952-dbfb-45e7-a245-02a3ea3ca955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/img</value>
      <webElementGuid>94309d3a-d8b1-442d-b352-34b6b60cca35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/cache/300/tPxBYm/2023/12/21/e223defa-a09f-4c36-b908-ab718a069745.png' and @alt = 'Al']</value>
      <webElementGuid>c898ea28-2b24-4ff9-8411-49e30df38630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/cache/300/tPxBYm/2023/1/20/a2749ea1-b938-49df-b53b-46e9ed28c016.jpg' and @alt = 'Al']</value>
      <webElementGuid>b645ef87-28a6-42a9-93b7-3ca72b0886c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
