<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ada yang baru di Mode Tampilan, lho__b93c91</name>
   <tag></tag>
   <elementGuidId>a03e94ce-e0ad-416e-a63f-5628de7c3855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coachmark']/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.unf-coachmark-v2__close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7d8cf2f-2900-4b95-9779-e1590120507f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unf-coachmark-v2__close-button</value>
      <webElementGuid>575f89e1-4b58-4555-adf2-c57d303358f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tutup</value>
      <webElementGuid>c27b7164-5858-4e29-8fef-1c9e02ebe3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coachmark&quot;)/div[@class=&quot;css-1f3byfw e1fhg8d32&quot;]/div[@class=&quot;unf-coachmark-v2__body&quot;]/div[2]/button[@class=&quot;unf-coachmark-v2__close-button&quot;]</value>
      <webElementGuid>7094ffb1-7653-4bbd-9f6c-d7a319ba4aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coachmark']/div/div/div[2]/button</value>
      <webElementGuid>66fa7d5f-872c-41d9-9f43-067a378d05b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>88e2a557-8242-4e42-8590-84b82e41e679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
