<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ada yang baru di Mode Tampilan, lho__b93c91_1</name>
   <tag></tag>
   <elementGuidId>7c579faf-e567-43ff-b2e7-c69601cba886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coachmark']/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.unf-coachmark-v2__close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5776df9d-258b-4cc2-aa88-8388e9281489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unf-coachmark-v2__close-button</value>
      <webElementGuid>1cba38e5-bafd-4d9f-a2da-92551c9c2119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tutup</value>
      <webElementGuid>1d4d4f47-7540-4e53-9c9e-8dfcd44b227e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coachmark&quot;)/div[@class=&quot;css-1p7is2a e1fhg8d32&quot;]/div[@class=&quot;unf-coachmark-v2__body&quot;]/div[2]/button[@class=&quot;unf-coachmark-v2__close-button&quot;]</value>
      <webElementGuid>d704d8ed-4901-4650-bfca-95f2b48d9167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coachmark']/div/div/div[2]/button</value>
      <webElementGuid>e288b785-ff8a-4d06-a478-bc7059dd5f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cbf24814-48f6-445a-994c-b12003cf96c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
