<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Al_profilePicture</name>
   <tag></tag>
   <elementGuidId>8072bf5b-ce69-496b-9c70-887576d8370c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profilePictureInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profilePictureInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a18285b-b7ef-4f76-b8b6-ef47115caed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1on728u</value>
      <webElementGuid>dd689151-8080-458f-8f7d-0e84f4783e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ffbc8f48-b312-41d3-a099-0ff41f8190e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profilePictureInput</value>
      <webElementGuid>8d4911fb-c8ab-451b-85fd-b75fde0d0677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profilePicture</value>
      <webElementGuid>cd36336b-238b-42ee-b474-262ed831254e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/jpeg, .jpeg, .jpg, image/png, .png</value>
      <webElementGuid>cb74a705-7b8d-4fa8-b968-1430214aaec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-change-picture</value>
      <webElementGuid>bba9da0e-ccc1-4677-a47d-3a0ad43cbcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profilePictureInput&quot;)</value>
      <webElementGuid>daa9f0b1-75c9-4e88-9ff7-39459b8e230f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profilePictureInput']</value>
      <webElementGuid>3cfd6cd7-c1ce-40b8-87e0-c68acacf0380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div[2]/div/section/input</value>
      <webElementGuid>27ae2f06-c37f-4593-9a19-2ac2d5fe8287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/input</value>
      <webElementGuid>4535814b-63f8-4be9-b4cd-3622f5f4a02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'profilePictureInput' and @name = 'profilePicture']</value>
      <webElementGuid>116f60fc-9a7c-4933-8d7b-ec7953c48e1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
