<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daftar</name>
   <tag></tag>
   <elementGuidId>9f06fbaa-49f5-4420-956f-3cecb421ed86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/main/div[2]/div[2]/div/div[2]/form/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-ijws95-unf-btn.eg8apji0 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4e6a289-a31c-4d14-b6c8-786c02ecd05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>fc7c7c17-38d8-46d0-8393-f3a31d19c792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/main[@class=&quot;css-nuukba&quot;]/div[@class=&quot;css-mu789q&quot;]/div[@class=&quot;right__container&quot;]/div[@class=&quot;css-1n9ywnk&quot;]/div[2]/form[1]/button[@class=&quot;css-ijws95-unf-btn eg8apji0&quot;]/span[1]</value>
      <webElementGuid>a0df66e5-bfdc-4ab1-8f97-1f77d5628213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/div[2]/div[2]/div/div[2]/form/button/span</value>
      <webElementGuid>d631d2a2-e0dd-457c-8b59-e5b95e28ebbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number or Email'])[1]/following::span[1]</value>
      <webElementGuid>b3e22e3b-4125-4f08-a162-c52f1a899705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau daftar dengan'])[1]/following::span[1]</value>
      <webElementGuid>13e02ed8-1601-4d20-945e-ea99585ea1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dengan mendaftar, saya menyetujui'])[1]/preceding::span[1]</value>
      <webElementGuid>d4672f6f-7d2a-4f36-810d-b57047554e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/preceding::span[1]</value>
      <webElementGuid>b6bfca3b-41b8-40d7-bd2f-3c2f082124e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>ef574cf7-effc-47ee-8267-b797e6de88b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>07a60dc2-fc18-474c-8463-309568e700a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>aad4f2bb-a8f8-4c77-bdb1-154bfa6dec0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
